export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_GET_PROFILE_START = 'AUTH_GET_PROFILE_START';
export const AUTH_GET_PROFILE_SUCCESS = 'AUTH_GET_PROFILE_SUCCESS';
export const AUTH_GET_PROFILE_FAIL = 'AUTH_GET_PROFILE_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_DONE_LOADING = 'AUTH_DONE_LOADING';
export const AUTH_SET_PASSWORD_RESET_CODE = 'AUTH_SET_PASSWORD_RESET_CODE';
export const AUTH_CLEAR_PASSWORD_RESET_CODE = 'AUTH_CLEAR_PASSWORD_RESET_CODE';

export const CHANGE_OPEN_SIDEBAR_NAV_GROUP = 'CHANGE_OPEN_SIDEBAR_NAV_GROUP';
export const GET_SET_BREADCRUMB = 'GET_SET_BREADCRUMB';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_ACTIVE_MODAL = 'SET_ACTIVE_MODAL';
export const SET_MODAL_MESSAGE = 'SET_MODAL_MESSAGE';

export const GET_USER_AGENT = 'GET_USER_AGENT';
export const GET_USER_IP_START = 'GET_USER_IP_START';
export const GET_USER_IP_SUCCESS = 'GET_USER_IP_SUCCESS';
export const GET_USER_IP_FAIL = 'GET_USER_IP_FAIL';

export const GEOLOCATE_LAT_LNG_START = 'GEOLOCATE_LAT_LNG_START';
export const GEOLOCATE_LAT_LNG_SUCCESS = 'GEOLOCATE_LAT_LNG_SUCCESS';
export const GEOLOCATE_GEOCODE_START = 'GEOLOCATE_GEOCODE_START';
export const GEOLOCATE_GEOCODE_SUCCESS = 'GEOLOCATE_GEOCODE_SUCCESS';
export const GEOLOCATE_GEOCODE_FAIL = 'GEOLOCATE_GEOCODE_FAIL';

export const SEARCH_FORM_UPDATE_ELEMENT = 'SEARCH_FORM_UPDATE_ELEMENT';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
export const SEARCH_PAGINATION_CHANGE_DONE = 'SEARCH_PAGINATION_CHANGE_DONE';
export const SEARCH_SORT_BY_CHANGE_DONE = 'SEARCH_SORT_BY_CHANGE_DONE';

export const SET_SAVED_SEARCH_START = 'SET_SAVED_SEARCH_START';
export const SET_SAVED_SEARCH_SUCCESS = 'SET_SAVED_SEARCH_SUCCESS';
export const SET_SAVED_SEARCH_FAIL = 'SET_SAVED_SEARCH_FAIL';
export const GET_SAVED_SEARCHES_START = 'GET_SAVED_SEARCHES_START';
export const GET_SAVED_SEARCHES_SUCCESS = 'GET_SAVED_SEARCHES_SUCCESS';
export const GET_SAVED_SEARCHES_FAIL = 'GET_SAVED_SEARCHES_FAIL';
export const USE_SAVED_SEARCH_START = 'USE_SAVED_SEARCH_START';
export const USE_SAVED_SEARCH_SUCCESS = 'USE_SAVED_SEARCH_SUCCESS';
export const USE_SAVED_SEARCH_FAIL = 'USE_SAVED_SEARCH_FAIL';
export const REMOVE_SAVED_SEARCH_START = 'REMOVE_SAVED_SEARCH_START';
export const REMOVE_SAVED_SEARCH_SUCCESS = 'REMOVE_SAVED_SEARCH_SUCCESS';
export const REMOVE_SAVED_SEARCH_FAIL = 'REMOVE_SAVED_SEARCH_FAIL';

export const SET_SAVED_JOB_START = 'SET_SAVED_JOB_START';
export const SET_SAVED_JOB_SUCCESS = 'SET_SAVED_JOB_SUCCESS';
export const SET_SAVED_JOB_FAIL = 'SET_SAVED_JOB_FAIL';
export const GET_SAVED_JOBS_START = 'GET_SAVED_JOBS_START';
export const GET_SAVED_JOBS_SUCCESS = 'GET_SAVED_JOBS_SUCCESS';
export const GET_SAVED_JOBS_FAIL = 'GET_SAVED_JOBS_FAIL';
export const REMOVE_SAVED_JOB_START = 'REMOVE_SAVED_JOB_START';
export const REMOVE_SAVED_JOB_SUCCESS = 'REMOVE_SAVED_JOB_SUCCESS';
export const REMOVE_SAVED_JOB_FAIL = 'REMOVE_SAVED_JOB_FAIL';

export const SET_SAVED_APPLICATION_START = 'SET_SAVED_APPLICATION_START';
export const SET_SAVED_APPLICATION_SUCCESS = 'SET_SAVED_APPLICATION_SUCCESS';
export const SET_SAVED_APPLICATION_FAIL = 'SET_SAVED_APPLICATION_FAIL';
export const GET_SAVED_APPLICATIONS_START = 'GET_SAVED_APPLICATIONS_START';
export const GET_SAVED_APPLICATIONS_SUCCESS = 'GET_SAVED_APPLICATIONS_SUCCESS';
export const GET_SAVED_APPLICATIONS_FAIL = 'GET_SAVED_APPLICATIONS_FAIL';
export const CHANGE_SAVED_APPLICATIONS_START = 'CHANGE_SAVED_APPLICATIONS_START';
export const CHANGE_SAVED_APPLICATIONS_SUCCESS = 'CHANGE_SAVED_APPLICATIONS_SUCCESS';
export const CHANGE_SAVED_APPLICATIONS_FAIL = 'CHANGE_SAVED_APPLICATIONS_FAIL';
export const REMOVE_SAVED_APPLICATION_START = 'REMOVE_SAVED_APPLICATION_START';
export const REMOVE_SAVED_APPLICATION_SUCCESS = 'REMOVE_SAVED_APPLICATION_SUCCESS';
export const REMOVE_SAVED_APPLICATION_FAIL = 'REMOVE_SAVED_APPLICATION_FAIL';
export const REMOVE_SAVED_APPLICATIONS_START = 'REMOVE_SAVED_APPLICATIONS_START';
export const REMOVE_SAVED_APPLICATIONS_SUCCESS = 'REMOVE_SAVED_APPLICATIONS_SUCCESS';
export const REMOVE_SAVED_APPLICATIONS_FAIL = 'REMOVE_SAVED_APPLICATIONS_FAIL';
