export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CHANGE_OPEN_SIDEBAR_NAV_GROUP = 'CHANGE_OPEN_SIDEBAR_NAV_GROUP';
export const GET_SET_BREADCRUMB = 'GET_SET_BREADCRUMB';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SET_ACTIVE_MODAL = 'SET_ACTIVE_MODAL';
export const SET_MODAL_MESSAGE = 'SET_MODAL_MESSAGE';

export const GET_USER_AGENT = 'GET_USER_AGENT';
export const GET_USER_IP_START = 'GET_USER_IP_START';
export const GET_USER_IP_SUCCESS = 'GET_USER_IP_SUCCESS';

export const GEOLOCATE_LAT_LNG_START = 'GEOLOCATE_LAT_LNG_START';
export const GEOLOCATE_LAT_LNG_SUCCESS = 'GEOLOCATE_LAT_LNG_SUCCESS';
export const GEOLOCATE_GEOCODE_START = 'GEOLOCATE_GEOCODE_START';
export const GEOLOCATE_GEOCODE_SUCCESS = 'GEOLOCATE_GEOCODE_SUCCESS';
export const GEOLOCATE_GEOCODE_FAIL = 'GEOLOCATE_GEOCODE_FAIL';

export const SEARCH_FORM_UPDATE_ELEMENT = 'SEARCH_FORM_UPDATE_ELEMENT';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
export const SEARCH_PAGINATION_CHANGE_DONE = 'SEARCH_PAGINATION_CHANGE_DONE';
