export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CHANGE_OPEN_SIDEBAR_NAV_GROUP = 'CHANGE_OPEN_SIDEBAR_NAV_GROUP';
export const GET_SET_BREADCRUMB = 'GET_SET_BREADCRUMB';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SET_ACTIVE_MODAL = 'SET_ACTIVE_MODAL';

export const GET_USER_IP_START = 'GET_USER_IP_START';
export const GET_USER_IP_SUCCESS = 'GET_USER_IP_SUCCESS';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
