export const countries = [
  { value: '', displayValue: 'Please select a Country', disabled: true },
  { value: 'ca', displayValue: 'Canada' },
  { value: 'us', displayValue: 'United States' },
  { value: 'dashes', displayValue: '----------', disabled: true },
  { value: 'ar', displayValue: 'Argentina' },
  { value: 'au', displayValue: 'Australia' },
  { value: 'at', displayValue: 'Austria' },
  { value: 'bh', displayValue: 'Bahrain' },
  { value: 'be', displayValue: 'Belgium' },
  { value: 'br', displayValue: 'Brazil' },
  { value: 'cl', displayValue: 'Chile' },
  { value: 'cn', displayValue: 'China' },
  { value: 'co', displayValue: 'Colombia' },
  { value: 'cz', displayValue: 'Czech Republic' },
  { value: 'dk', displayValue: 'Denmark' },
  { value: 'fi', displayValue: 'Finland' },
  { value: 'fr', displayValue: 'France' },
  { value: 'de', displayValue: 'Germany' },
  { value: 'gr', displayValue: 'Greece' },
  { value: 'hk', displayValue: 'Hong Kong' },
  { value: 'hu', displayValue: 'Hungary' },
  { value: 'in', displayValue: 'India' },
  { value: 'id', displayValue: 'Indonesia' },
  { value: 'ie', displayValue: 'Ireland' },
  { value: 'il', displayValue: 'Israel' },
  { value: 'it', displayValue: 'Italy' },
  { value: 'jp', displayValue: 'Japan' },
  { value: 'kr', displayValue: 'Korea' },
  { value: 'kw', displayValue: 'Kuwait' },
  { value: 'lu', displayValue: 'Luxembourg' },
  { value: 'my', displayValue: 'Malaysia' },
  { value: 'mx', displayValue: 'Mexico' },
  { value: 'nl', displayValue: 'Netherlands' },
  { value: 'nz', displayValue: 'New Zealand' },
  { value: 'no', displayValue: 'Norway' },
  { value: 'om', displayValue: 'Oman' },
  { value: 'pk', displayValue: 'Pakistan' },
  { value: 'pe', displayValue: 'Peru' },
  { value: 'ph', displayValue: 'Philippines' },
  { value: 'pl', displayValue: 'Poland' },
  { value: 'pt', displayValue: 'Portugal' },
  { value: 'qt', displayValue: 'Qatar' },
  { value: 'ro', displayValue: 'Romania' },
  { value: 'ru', displayValue: 'Russia' },
  { value: 'sa', displayValue: 'Saudi Arabia' },
  { value: 'sg', displayValue: 'Singapore' },
  { value: 'za', displayValue: 'South Africa' },
  { value: 'es', displayValue: 'Spain' },
  { value: 'se', displayValue: 'Sweden' },
  { value: 'ch', displayValue: 'Switzerland' },
  { value: 'tw', displayValue: 'Taiwan' },
  { value: 'th', displayValue: 'Thailand' },
  { value: 'tr', displayValue: 'Turkey' },
  { value: 'ae', displayValue: 'United Arab Emirates' },
  { value: 'gb', displayValue: 'United Kingdom' },
  { value: 've', displayValue: 'Venezuela' },
  { value: 'vn', displayValue: 'Vietnam' }
]
